// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ1kZIG6dXHHekLVUAGHaTyGzOD8UVQYY',
    appId: '1:911680739260:web:d4ec26b123a0efe3a97db9',
    messagingSenderId: '911680739260',
    projectId: 'rng-capitalist',
    authDomain: 'rng-capitalist.firebaseapp.com',
    storageBucket: 'rng-capitalist.firebasestorage.app',
    measurementId: 'G-ZC6VXVBGTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOnDhjZCVIDZWRtmCNU1GSce8iZxEmI3A',
    appId: '1:911680739260:android:50c5348ee071f78ba97db9',
    messagingSenderId: '911680739260',
    projectId: 'rng-capitalist',
    storageBucket: 'rng-capitalist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgtFStl1aDRto-26vXvvgGy7Vz6eRcxXY',
    appId: '1:911680739260:ios:ed47b1f068ac6d94a97db9',
    messagingSenderId: '911680739260',
    projectId: 'rng-capitalist',
    storageBucket: 'rng-capitalist.firebasestorage.app',
    iosBundleId: 'com.example.rngCapitalist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgtFStl1aDRto-26vXvvgGy7Vz6eRcxXY',
    appId: '1:911680739260:ios:ed47b1f068ac6d94a97db9',
    messagingSenderId: '911680739260',
    projectId: 'rng-capitalist',
    storageBucket: 'rng-capitalist.firebasestorage.app',
    iosBundleId: 'com.example.rngCapitalist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ1kZIG6dXHHekLVUAGHaTyGzOD8UVQYY',
    appId: '1:911680739260:web:fbdd52a2663dba87a97db9',
    messagingSenderId: '911680739260',
    projectId: 'rng-capitalist',
    authDomain: 'rng-capitalist.firebaseapp.com',
    storageBucket: 'rng-capitalist.firebasestorage.app',
    measurementId: 'G-H4H14NXZF1',
  );

}

// TODO: Replace the placeholder values above with your actual Firebase configuration
// You can get these values from the Firebase Console after setting up your project