name: rng_capitalist
description: AI-Powered Sunk Cost Tracker - Let intelligent chaos manage your wallet with Google Gemini AI
version: 2.2.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  http: ^1.1.0
  plaid_flutter: ^4.0.0
  local_notifier: ^0.1.6
  audioplayers: ^5.2.1
  # Firebase dependencies
  firebase_core: ^2.15.1
  # firebase_auth: ^4.9.0  # Disabled - Windows build issues
  # google_sign_in: ^6.1.4  # Disabled - causes Windows build issues  
  cloud_firestore: ^4.9.1
  # Unique user ID generation
  crypto: ^3.0.3
  # Advanced features
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.9.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  fl_chart: ^0.64.0
  image: ^4.1.3
  # File handling and AI processing
  file_picker: ^6.1.1
  syncfusion_flutter_pdf: ^26.2.14
  # Google Gemini AI for intelligent document analysis
  google_generative_ai: ^0.4.3
  # Environment variables support
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.2
  # Microsoft Store packaging
  msix: ^3.16.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - .env

# MSIX configuration for Microsoft Store
msix_config:
  display_name: "RNG Capitalist"
  publisher_display_name: "A-PLUS"
  identity_name: "A-PLUS.RNGCapitalist"
  package_family_name: "A-PLUS.RNGCapitalist_kq2gpd5ks5v86"
  msix_version: "2.2.0.0"
  description: "AI-Powered D&D Budget Tracker with smart analytics and cloud sync. Track your tabletop gaming expenses with intelligent categorization and real-time collaboration."
  publisher: "CN=25D94FEB-B89E-4816-BB32-35995EAF1AFB"
  logo_path: "assets/logo/app_icon.png"
  start_menu_icon_path: "assets/logo/app_icon.png"
  tile_icon_path: "assets/logo/app_icon.png"
  vs_generated_images_folder_path: "assets/logo/"
  icons_background_color: "#663399"
  architecture: "x64"
  languages: "en-us"
  capabilities: "internetClient,internetClientServer,privateNetworkClientServer"
  store: true