name: rng_capitalist
description: Let chaos manage your wallet
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  http: ^1.1.0
  plaid_flutter: ^4.0.0
  local_notifier: ^0.1.6
  audioplayers: ^5.2.1
  # Firebase dependencies
  firebase_core: ^2.15.1
  # firebase_auth: ^4.9.0  # Disabled - Windows build issues
  # google_sign_in: ^6.1.4  # Disabled - causes Windows build issues  
  cloud_firestore: ^4.9.1
  # Unique user ID generation
  crypto: ^3.0.3
  # Advanced features
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.9.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  fl_chart: ^0.64.0
  image: ^4.1.3
  # File handling and AI processing
  file_picker: ^6.1.1
  syncfusion_flutter_pdf: ^26.2.14
  # Google Gemini AI for intelligent document analysis
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/